name: yawf
base: core24
grade: stable
confinement: strict
adopt-info: yawf
license: GPL-3.0
website: https://github.com/Wahid7852/YAWF
icon: resource/image/icons/hicolor/256x256/apps/io.github.wahid7852.YAWF.png

platforms:
  amd64:
  arm64:

parts:
  yawf:
    source-type: local
    source: .
    plugin: cmake
    override-pull: |
      craftctl default
      sed -i.bak -e 's|Icon=${WIL_ICON}|Icon=usr/local/share/icons/hicolor/256x256/apps/io.github.wahid7852.YAWF.png|g' resource/desktop/io.github.wahid7852.YAWF.desktop.in
    override-build: |
      export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      unset LD_LIBRARY_PATH
      unset PKG_CONFIG_PATH
      cmake "$SNAPCRAFT_PART_SRC" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr/local
      cmake --build . -- -j$(nproc)
      cmake --install . --destdir "$SNAPCRAFT_PART_INSTALL"
    build-packages:
      - intltool
      - libglib2.0-dev-bin
      - libcanberra-dev
      - libsigc++-2.0-dev
      - libgtkmm-3.0-dev
      - libwebkit2gtk-4.1-dev
      - libayatana-appindicator3-dev
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - glib-networking
      - libglu1-mesa
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav
    parse-info:
      - resource/io.github.wahid7852.YAWF.metainfo.xml

slots:
  dbus-app:
    interface: dbus
    bus: session
    name: io.github.wahid7852.YAWF

apps:
  yawf:
    command: usr/local/bin/yawf
    extensions: [gnome]
    common-id: io.github.wahid7852.YAWF
    desktop: usr/local/share/applications/io.github.wahid7852.YAWF.desktop
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - network
      - network-manager
      - network-manager-observe
      - network-status
      - browser-support
      - system-observe
      - process-control
      - camera
      - audio-playback
      - audio-record
      - home
      - removable-media
      - upower-observe
      - screen-inhibit-control
    slots:
      - dbus-app

assumes:
  - snapd2.63
